webproject/webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'
urlpatterns = [

    path('',views.main,name= 'main'),
    path('<int:mov_id>/',views.details, name='details') ,
    path('add/',views.add_movie, name= 'add_movie') ,
    path('update/<int:id>/', views.update, name= 'update'),
    path('delete/<int:id>/', views.delete, name= 'delete')
]

webproject/webproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webapp.urls')) ,
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

webproject/webapp/models.py
from django.db import models


# Create your models here.

class Movies(models.Model):
    name = models.CharField(max_length=230)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='image')

webproject/webapp/forms.py
from django import forms
from . models import Movies

class MoviesForm(forms.ModelForm):
    class Meta:
        model= Movies
        fields=[
            'name','desc','year','img'
        ]

webproject/webapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movies
from .forms import MoviesForm


# Create your views here.

def main(req):
    obj = Movies.objects.all()
    return render(req, 'index.html', {'object1': obj})


def details(request, mov_id):
    movie = Movies.objects.get(id=mov_id)
    return render(request, 'details.html', {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']

        movie = Movies(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, 'add.html')


# forms.py

def update(request, id):
    movie = Movies.objects.get(id=id)
    form = MoviesForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request,id):
    if request.method=='POST':
        movie= Movies.objects.get(id= id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

webproject/templates/add.html
{% extends 'base.html' %}

{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter the name"> <br>
    <input type="text" name="desc" placeholder="Enter the details"><br>
    <input type="number" name="year"><br>
    <input type="file" name="img">
    <input type="submit">
</form>

{% endblock %}

webproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">ZAG MOVIES</a>
  </div>
</nav>

{% block body%}
{% endblock %}

</body>
</html>

webproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you want to delete this movie?
    <input type="submit">
</form>

webproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
{{movie.id}}
<br>
<div class="container">

    <div class="row">


    <div class="col-md-6">
        <img src="{{movie.img.url}}" width="300" height="500" >
    </div>
    <div class="col-md-6">

    <h4 style="color: grey">{{movie.name}}<br></h4>
    <h2>{{movie.desc}}<br></h2>
    {{movie.year}}<br>


<a  class="btn btn-warning" href="{% url 'webapp:update' movie.id %}">update</a>
<a  class="btn btn-danger" href="{% url 'webapp:delete' movie.id %}">delete</a>

    </div>
</div>
</div>

{% endblock %}

webproject/templates/edit.html
<form method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

webproject/templates/index.html
{% extends 'base.html' %}

{% block body %}





<div class="container" style="margin-top: 40px">


    <div class="row">
        {% for i in object1 %}
        <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="150">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <a href="{% url  'webapp:details' i.id %}" class="btn btn-primary" style="align-item: center">MORE</a>
                    </div>
                </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}